//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFitness.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int PId { get; set; }
        public string PDuration { get; set; }
        public string PPrice { get; set; }
        public string PDesc { get; set; }
    }
}
