//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFitness.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int id { get; set; }
        public Nullable<int> pid { get; set; }
        public Nullable<int> uid { get; set; }
        public string orderId { get; set; }
        public string payId { get; set; }
        public string checksum { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string status { get; set; }
    }
}
