//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFitness.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public int RId { get; set; }
        public Nullable<int> UId { get; set; }
        public Nullable<int> PId { get; set; }
        public Nullable<System.DateTime> RDate { get; set; }
    }
}
