//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFitness.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UId { get; set; }
        public string UName { get; set; }
        public string UEmail { get; set; }
        public string UPassword { get; set; }
    }
}
